baseURL = "https://gcgan.github.io/"
languageCode = "zh-CN"
title = "Gc's Code"

theme = "mainroad"
mainSections = ["posts"]


[[menu.main]]
name="首页"
url="/"
weight="1"
[[menu.main]]
name="关于我"
url="/aboutme"
weight="2"
