baseURL = "https://gcgan.github.io/"
languageCode = "zh-CN"
title = "Gc's Code"

theme = "mainroad"
mainSections = ["posts"]
readmore = true
dateformat = "2006-01-02"
# sidebar = "right"


[[menu.main]]
name="首页"
url="/"
weight="1"
[[menu.main]]
name="关于我"
url="/aboutme"
weight="2"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]
